vim.opt.encoding = "UTF-8"
vim.opt.fileencoding = "utf-8"
vim.opt.scrolloff = 8 -- 移动保持光标周围8行
vim.opt.sidescrolloff = 8
vim.opt.number = true -- 行号
vim.opt.relativenumber = true -- 相对行号
vim.opt.cursorline = true -- 高亮所在行
vim.opt.signcolumn = "yes" -- 显示左侧图标指示列
vim.opt.tabstop = 2
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftround = true
vim.opt.shiftwidth = 2
vim.opt.shiftwidth = 2
vim.opt.autoindent = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.incsearch = true
vim.opt.cmdheight = 1
vim.opt.autoread = true
vim.opt.autoread = true
vim.opt.hidden = true
vim.opt.mouse = "a"
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.swapfile = false
vim.opt.updatetime = 300
vim.opt.timeoutlen = 500 -- 等待键盘快捷键连击时间
vim.opt.splitbelow = true
vim.opt.splitright = true
-- vim.g.completeopt = "menu,menuone,noselect,noinsert"
vim.opt.completeopt = "menu,menuone,noselect,noinsert" -- 自动补全不自动选中
vim.opt.termguicolors = true
vim.opt.termguicolors = true
vim.opt.list = false
vim.opt.listchars = "space:·,tab:··"
vim.opt.wildmenu = true
vim.opt.shortmess = vim.o.shortmess .. "c"
vim.opt.pumheight = 10
vim.opt.showtabline = 2
vim.opt.showmode = false -- vim 自带的模式提示
vim.opt.clipboard = "unnamedplus"
vim.opt.undofile = true -- 无限撤消
